/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#006d43",
        "on-secondary-fixed-variant": "#3a485b",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#edf1f5",
        "on-primary-fixed-variant": "#005231",
        "surface": "#f6fafe",
        "tertiary-container": "#4ba175",
        "surface-variant": "#dfe3e7",
        "outline-variant": "#bccabe",
        "primary-container": "#00a669",
        "surface-container-low": "#f0f4f8",
        "tertiary-fixed-dim": "#82d8a8",
        "primary-fixed": "#79fbb5",
        "on-primary-fixed": "#002111",
        "surface-bright": "#f6fafe",
        "inverse-primary": "#5bde9b",
        "on-secondary-fixed": "#0d1c2e",
        "secondary-fixed": "#d5e3fc",
        "primary": "#006d43",
        "primary-fixed-dim": "#5bde9b",
        "on-tertiary-container": "#00311d",
        "on-surface-variant": "#3d4a41",
        "on-surface": "#171c1f",
        "background": "#f6fafe",
        "surface-container-high": "#e4e9ed",
        "surface-container": "#eaeef2",
        "error": "#ba1a1a",
        "outline": "#6d7a70",
        "tertiary-fixed": "#9df5c3",
        "on-secondary-container": "#57657a",
        "secondary": "#515f74",
        "on-tertiary-fixed": "#002112",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#b9c7df",
        "surface-dim": "#d6dade",
        "on-error": "#ffffff",
        "on-background": "#171c1f",
        "secondary-container": "#d5e3fc",
        "on-tertiary-fixed-variant": "#005233",
        "tertiary": "#036c45",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dfe3e7",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-container": "#00311c",
        "inverse-surface": "#2c3134",
        "surface-container-lowest": "#ffffff",
        emerald: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
        },
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
