import * as XLSX from 'xlsx';
import { STEPS_CONFIG } from '../../reports/types';

/**
 * GET /api/download-brsr-template
 * Streams a pre-formatted .xlsx template with every BRSR Principle 6
 * data-entry field.  The consumer fills Column E and uploads it back.
 */
export async function GET() {
  const wb = XLSX.utils.book_new();

  // ── Instructions sheet ───────────────────────────────────────────────────────
  const instructions: (string | number)[][] = [
    ['BRSR Principle 6 — Environmental Data Entry Template'],
    ['Generated by ESGtech.ai'],
    [''],
    ['INSTRUCTIONS'],
    ['─────────────────────────────────────────────────────────────────────────────'],
    ['1.  Only fill in the "FY 2024-25 Value" column (Column E).'],
    ["2.  Do NOT edit Column A (internal key) — it is used when the file is imported."],
    ['3.  Do NOT add, remove, or reorder rows in the "Data Entry" sheet.'],
    ['4.  Leave a cell blank (or enter 0) if the value does not apply.'],
    ["5.  RevenuePPP (Row marked 'RevenuePPP') will be auto-calculated on import."],
    ['    You may override it if you have a precise figure.'],
    ['6.  Save the file as .xlsx and upload it using the Upload Excel button.'],
    [''],
    ['UNITS REFERENCE'],
    ['─────────────────────────────────────────────────────────────────────────────'],
    ['  Energy        →  GJ (Gigajoules)'],
    ['  Water         →  kL (Kilolitres)'],
    ['  Air emissions →  MT (Metric Tonnes)'],
    ['  GHG           →  tCO₂Eq (Tonnes CO₂ equivalent)'],
    ['  Waste         →  MT (Metric Tonnes)'],
    ['  Revenue       →  ₹ Crores'],
    ['  Production    →  MT (Metric Tonnes of output)'],
  ];

  const wsInstructions = XLSX.utils.aoa_to_sheet(instructions);
  wsInstructions['!cols'] = [{ wch: 80 }];
  XLSX.utils.book_append_sheet(wb, wsInstructions, 'Instructions');

  // ── Data Entry sheet ─────────────────────────────────────────────────────────
  const HEADER_ROW = [
    'Internal Key (DO NOT EDIT)',
    'Section',
    'Category',
    'Parameter',
    'FY 2024-25 Value',
    'Unit',
    'Notes / Tips',
  ];

  const dataRows: (string | number)[][] = [HEADER_ROW];

  for (const step of STEPS_CONFIG) {
    dataRows.push([
      step.key,           // A — internal key
      step.section,       // B — Q1 / Q3 / Q4 etc.
      step.category,      // C — category label
      step.title,         // D — human-readable name
      '',                 // E — USER FILLS THIS
      step.unit,          // F — unit
      step.tip,           // G — helper text
    ]);
  }

  const wsData = XLSX.utils.aoa_to_sheet(dataRows);

  // Column widths
  wsData['!cols'] = [
    { wch: 30 },   // A — internal key
    { wch: 8 },    // B — section
    { wch: 22 },   // C — category
    { wch: 56 },   // D — parameter
    { wch: 22 },   // E — value (user entry)
    { wch: 12 },   // F — unit
    { wch: 64 },   // G — tips
  ];

  XLSX.utils.book_append_sheet(wb, wsData, 'Data Entry');

  // ── Write & return ───────────────────────────────────────────────────────────
  const buffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });

  return new Response(buffer, {
    status: 200,
    headers: {
      'Content-Type':
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition':
        'attachment; filename="BRSR_P6_Template_FY2024-25.xlsx"',
    },
  });
}
